blueprint:
  name: Front Door Ring Button and Unlock Action
  description: Automation to unlock the front door when the door ring button is pressed and notification action is UNLOCK_DOOR
  domain: automation
  input:
    binary_sensor_entity:
      name: Binary Sensor
      description: The binary sensor that triggers the automation
      selector:
        entity:
          domain: binary_sensor
    lock_entity:
      name: Lock
      description: The lock to unlock when the event is triggered
      selector:
        entity:
          domain: lock
    timer_entity:
      name: Timer
      description: The timer to start when the door ring button is pressed
      selector:
        entity:
          domain: timer
    camera_entity:
      name: Camera
      description: The camera that captures the event
      selector:
        entity:
          domain: camera

trigger:
  - platform: state
    entity_id: !input binary_sensor_entity
    from: "off"
    to: "on"
  - platform: event
    event_type: mobile_app_notification_action
    event_data:
      action: UNLOCK_DOOR

condition: []

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >-
              {{ trigger.platform == 'event' and trigger.event.data.action ==
              'UNLOCK_DOOR' }}
        sequence:
          - service: lock.unlock
            entity_id: !input lock_entity
      - conditions:
          - condition: state
            entity_id: !input timer_entity
            state: idle
          - condition: template
            value_template: >-
              {{ trigger.platform == 'state' and trigger.to_state.state == 'on'
              }}
        sequence:
          - service: timer.start
            entity_id: !input timer_entity
            data:
              duration: "00:00:30"
          - service: notify.notify
            data:
              message: Someone is at the front door!
              title: Front Door Ringing
              data:
                entity_id: !input camera_entity
                actions:
                  - action: UNLOCK_DOOR
                    title: Unlock Door
mode: single
